Pustak/Models/Brand.cs
using Pustak.Models.BaseModel;

namespace Pustak.Models
{
    public class Brand : BaseEntity
    {
        public string Name { get; set; } = null!;
        public ICollection<Product>? Products { get; set; }
        public Brand()
        {
            Products = new HashSet<Product>();
        }
    }
}

Pustak/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pustak.Data;
using Pustak.Models;
using Pustok.Areas.Admin.Dtos;

namespace Pustak.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BrandController : Controller
    {
        private readonly AppDbContext _context;

        public BrandController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var authors = await _context.Brands.Where(x => !x.IsDeleted).ToListAsync();
            return View(authors);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BrandCreateDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }

            var isExist = await _context.Brands.AnyAsync(x => x.Name.ToLower() == dto.Name.ToLower());
            if (isExist)
            {
                ModelState.AddModelError("Name", "Brand already exist");
                return View(dto);
            }
            Brand brand = new Brand() { Name = dto.Name };

            await _context.Brands.AddAsync(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int id)
        {
            var brand = await _context.Brands.FirstOrDefaultAsync(x => x.Id == id);

            if (brand is null)
            {
                return NotFound();
            }

            BrandUpdateDto dto = new() { Name = brand.Name };
            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, BrandUpdateDto dto)
        {
            var existBrand = await _context.Brands.FirstOrDefaultAsync(x => x.Id == id);
            if (existBrand is null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(dto);
            }

            var isExist = await _context.Brands.AnyAsync(x => x.Name.ToLower() == dto.Name.ToLower() && x.Id != id);

            if (isExist)
            {
                ModelState.AddModelError("Name", "Brand alredy exist");
                return View(dto);
            }

            existBrand.Name = dto.Name;
            _context.Brands.Update(existBrand);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var brand = await _context.Brands.FirstOrDefaultAsync(x => x.Id == id);
            if (brand is null)
                return NotFound();

            brand.IsDeleted = true;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Pustak/Areas/Admin/Views/Brand/Create.cshtml
@* @model BrandCreateDto

<form method="post">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" asp-for="Name" placeholder="Enter name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div asp-validation-summary="ModelOnly" class="text-danger">  </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
 *@

Pustak/Areas/Admin/Views/Brand/Index.cshtml
@model List<Brand>

@{
    int count = 1;
}
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <p class="mb-4">
        DataTables is a third party plugin that is used to generate the demo table below.
        For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.
    </p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="dataTable_length"><label>Show <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div><div class="col-sm-12 col-md-6"><div id="dataTable_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label></div></div></div><div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 100.2px;">#</th>
                                        <th class="sorting sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 295.2px;">Brand Name</th>
                                        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="2" aria-label="Position: activate to sort column ascending" style="width: 196.2px;">Actions</th>
                                    </tr>
                                </thead>
                                <tbody id="tbody">
                                    @foreach (var brand in Model)
                                    {
                                        <tr class="odd">
                                            <td class="sorting_1">@(count++)</td>
                                            <td class="sorting_1">@brand.Name</td>
                                            <td><a class="btn deleteBtn btn-danger" asp-controller="Brand" asp-action="Delete" asp-route-id="@brand.Id">Delete</a></td>
                                            <td><a class="btn btn-warning" asp-controller="Brand" asp-action="Update" asp-route-id="@brand.Id">Update</a></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div><div class="row"><div class="col-sm-12 col-md-5"><div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div></div><div class="col-sm-12 col-md-7"><div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="dataTable_previous"><a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next" id="dataTable_next"><a href="#" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a></li></ul></div></div></div>
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: "btn btn-success",
                cancelButton: "btn btn-danger"
            },
            buttonsStyling: false
        });

        const deleteBtn = document.querySelectorAll(".deleteBtn");
        deleteBtn.forEach(x => {
            x.addEventListener("click", function (e) {
                e.preventDefault();
                swalWithBootstrapButtons.fire({
                    title: "Are you sure?",
                    text: "You won't be able to revert this!",
                    icon: "warning",
                    showCancelButton: true,
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel!",
                    reverseButtons: true
                }).then((result) => {
                    if (result.isConfirmed) {

                        const categoryId = this.dataset.id;
                        console.log(categoryId);
                        $.ajax({
                            type: "POST",
                            url: `Category/Delete/${categoryId}`,
                            success: function (res) {
                                console.log(res)
                                $("#tbody").html(res);
                            },
                            error: function (err) {
                                console.log(err)
                            }
                        })

                    } else if (
                        /* Read more about handling dismissals below */
                        result.dismiss === Swal.DismissReason.cancel
                    ) {
                        swalWithBootstrapButtons.fire({
                            title: "Cancelled",
                            text: "Your imaginary file is safe :)",
                            icon: "error"
                        });
                    }
                });
            })
        })</script>
}

Pustak/Areas/Admin/Views/Brand/Update.cshtml
@* @model BrandUpdateDto

<form method="post">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input class="form-control" asp-for="Name" placeholder="Enter name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div asp-validation-summary="ModelOnly" class="text-danger">  </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form> *@